apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: legal-recovery

resources:
  - namespace.yaml
  - configmap.yaml
  - api-deployment.yaml
  - api-service.yaml
  - web-deployment.yaml
  - web-service.yaml
  - ingress.yaml

secretGenerator:
  - name: legal-recovery-secrets
    behavior: create
    envs:
      - secrets/.env.secret
    options:
      disableNameSuffixHash: true

generatorOptions:
  disableNameSuffixHash: true
