version: "3.8"

services:
  prisma-runner:
    image: node:20-alpine
    working_dir: /app/apps/api
    environment:
      DATABASE_URL: "postgresql://lrdev:***@172.18.0.4:5432/legal_recovery?schema=public"
    volumes:
      - ../../:/app
    command: sh -c "cd /app && npm install && cd /app/apps/api && npx prisma migrate dev --name init"
    networks:
      - docker_default
    depends_on:
      postgres:
        condition: service_healthy

networks:
  docker_default:
    external: true
